language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit
# command to run tests
script:
  - DB_PORT=5432 DB_HOST=127.0.0.1 DB_USER=admin DB_PASS=postgrespassword DB_NAME=postgres pytest -s tests/