language: python
python:
  - "3.7"
services:
  - postgresql
install:
  - pip install -r requirements.txt
cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - DB_PORT=5432 DB_HOST=127.0.0.1 DB_USER=postgres DB_NAME=travis_ci_test pytest -s tests/