language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit
# command to run tests
#script:
#  - pytest -s tests/